module: MaterialMotionCoreAnimationTransitions
module_version: 1.0.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotionCoreAnimationTransitions.xcworkspace
  - -scheme
  - MaterialMotionCoreAnimationTransitions
github_url: https://github.com/material-motion/coreanimation-transitions-swift
github_file_prefix: https://github.com/material-motion/coreanimation-transitions-swift/tree/v1.0.0
